---
  # FILEPATHs
  XML_FILEPATH: 'Environment_Files/environment.xml'
  EXR_FILEPATH: 'Rendered_Files/environment.exr'
  JPG_FILEPATH: 'Rendered_Files/environment.jpg'
  
  # PHYSICAL LOCATION OF ENVIRONMENT
  LATITUDE: 34.052235
  LONGITUDE: -118.243683
  ELEVATION: 0.0

  # START DATE OF SIMULATION
  START_DATE: "2021-09-07"

  # ADD PATH DEPTH FOR INTEGRATOR AND RESOLUTION OF IRRADIANCE

