---
  # FILEPATHs
  EMPTY_XML_FILEPATH: 'Environment_Files/empty_environment.xml'
  MODIFIED_XML_FILEPATH: 'Environment_Files/modified_environment.xml'
  EXR_FILEPATH: 'Rendered_Files/render.exr'
  JPG_FILEPATH: 'Rendered_Files/render.jpg'
  PLANT_INFO_FILEPATH: 'Information_Files/plant_info.json'
  
  DAY_SIZE_RESOLUTION: 24

  # PHYSICAL LOCATION OF ENVIRONMENT
  LATITUDE: 34.052235
  LONGITUDE: -118.243683
  ELEVATION: 0.0

  # START DATE OF SIMULATION
  START_DATE: "2021-09-07"

  # ADD PATH DEPTH FOR INTEGRATOR AND RESOLUTION OF IRRADIANCE

